# Generated by Django 6.0.6 on 2026-07-01 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('meta_keywords', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('site_logo', models.ImageField(upload_to='site_logo/')),
                ('site_favicon', models.ImageField(upload_to='site_favicon/')),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('contact_phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_pan', models.IntegerField()),
                ('company_vat', models.IntegerField()),
                ('verification_code', models.CharField(max_length=255)),
                ('is_verfied', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('company_pan', 'Company PAN'), ('company_vat', 'Company VAT')], max_length=20)),
                ('document_name', models.CharField(max_length=255)),
                ('document_file', models.FileField(upload_to='company_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app_ecomweb.websitesettings')),
            ],
        ),
    ]
